spring.application.name=ProductCatalogServiceProxy

# 1. Database Connection - Standard for MySQL
# Ensure the database '' is created in your MySQL instance

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=Gufiralah@123

# 2. Hibernate Settings - Optimized for MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Use the MySQL dialect so Hibernate generates MySQL-compatible queries
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect